### ISSUE TITLE
Grower can manage site images

### ISSUE THREAD

**Issue by nluk01** [Slowers-Team/Slowers-App#100]
**Acceptance criteria**

- [x]  There is a placeholder for primary image on site's flexbox.
- [x]  Grower can see root site's image on flexbox.
- [x]  There can be many images on site page.
- [x]  Fetching site's image from the database.
- [x] Grower can add pictures for sites
- [x] Grower can delete site pictures

**Comment by Eoyie** [comment]
I think this issue has already been closed through a PR
