### ISSUE TITLE
User can see site images in the site flexbox

### ISSUE THREAD

**Issue by nluk01** [Slowers-Team/Slowers-App#148]
There was missing a feature that the grower can set an image to the site flexbox in the user story` #100 grower can manage site images`. The site flexbox  currently always displays only the placeholder image when creating a new site.

The placeholder image is displayed on the site flexbox automatically if the grower hasn't uploaded any image on the site. However if the grower has uploaded one image, it should be automatically displayed on the site flexbox. The grower can choose what image will be shown on the site flexbox if there are many image on the site.
<br />
<br />

_**Screenshot of the site flexbox's placeholder image:**_

![image](https://github.com/user-attachments/assets/83e07e8d-01db-4d58-89d2-2cf3a6753eea)

<br />
<br />
<br />

_**Ideas how to implement this feature:**_

_Option 1:_  The site images are shown on the image carousel. There could be a button for each image to select the image to the site flexbox.

_Option 2:_ There could be a button "Edit" on the site flexbox itself where the grower can choose which image will be displayed on the flexbox.

**Comment by Eoyie** [comment]
The same style of implementation as in the flower image in flower list will be done here!
