### ISSUE TITLE
Deleting a flower causes all flowers with the same name to disappear from view

### ISSUE THREAD

**Issue by amandahamynen** [Slowers-Team/Slowers-App#40]
**Description of the bug**
When a user views a list of flowers on browser, and there happens to be two different flowers with the same name (LatinName does not have to be the same), a deletion of one of them causes all of the same-named-flowers also disappear from the view. Rest of the same-named-flowers reappear after the page is reloaded.

**Steps to reproduce the bug**
1. On the browser, go to "/" (as of now, at least) to view the list of flowers.
2. Make sure that the database has at least two flowers with the same name.
3. Click a delete-button on one of the flowers.
4. See how not only did the flower you meant to delete disappear from the view, but also the other flower(s) which happened to have the same name.
5. Refresh the page.
6. The other(s) flower(s) with the same name is/are once again shown in the list of flowers.

**Expected behaviour**
When deleting a flower, only that flower disappears from the view even if the list has other flowers with the same name.

**Comment by Halmela** [comment]
https://github.com/Slowers-Team/Slowers-App/blob/8bc1e5587de3e0c49525135da56a73e316a7b6b8/frontend/src/pages/HomePage.jsx#L32

Flowers are deleted from view using name. Deleting by id would solve this.
