### ISSUE TITLE
When adding a site, the 'flowers' field is not saved to the database

### ISSUE THREAD

**Issue by VSirvio** [Slowers-Team/Slowers-App#54]
**Description of the bug**
When a new site is added via the backend and it has some flowers set in its 'flowers' field, the 'flowers' field of the newly created 'site' document in the database will still be empty.

**Steps to reproduce the bug**
1. Send to `/api/sites` a `POST` request e.g. with the body `{"name": "Greenhouse A", "flowers": ["66fd466f0011335cd891aea8"]}`
2. Run `mongosh Slowers --eval "db.sites.find()"` and the result will be something like
```
[
  {
    _id: ObjectId('66ffe1263100b0f2df710e67'),
    name: 'Greenhouse A',
    added_time: ISODate('2024-10-04T12:35:50.328Z'),
    note: '',
    parent: null,
    flowers: [],
    owner: null
  }
]
```

**Expected behavior**
The output of the command `mongosh Slowers --eval "db.sites.find()"` should have flower IDs correctly in the 'flowers' field e.g. like
```
[
  {
    _id: ObjectId('66ffe1263100b0f2df710e67'),
    name: 'Greenhouse A',
    added_time: ISODate('2024-10-04T12:35:50.328Z'),
    note: '',
    parent: null,
    flowers: [
      ObjectId('66fd466f0011335cd891aea8')
    ],
    owner: null
  }
]
```

**Comment by amandahamynen** [comment]
Thank you so much for pointing this out and being really observant (as per usual), @VSirvio ! It seems that I forgot to update addSite-function, and the problem is at line 46 in site.go:

```go
newSite := Site{Name: site.Name, Note: site.Note, AddedTime: time.Now(),
		Parent: site.Parent, Flowers: make([]*primitive.ObjectID, 0), Owner: &userID}
```

I’ll fix this quickly, and send you the request to review the PR if that’s okay? :)
